# Do not run on production
name: Seed (dev) faker data

on:
  workflow_dispatch:  

env:
  CLUSTER: https://api.gold.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.OC_AUTH_TOKEN }}
  TOOLS_TOKEN: ${{ secrets.OC_TOOLS_TOKEN }}
  PROJECT: tcloud
  ENV: dev

jobs:
  seed_faker_data:
    name: Seed dev faker data
    environment: dev
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      OS_NAMESPACE_SUFFIX: dev
      AUTH_TOKEN: ${{ secrets.OC_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ENV file
        run: cp .env.example .env
      - name: Cache OpenShift CLI
        id: cache-oc
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/oc
          key: ${{ runner.os }}-oc
      - name: Install OpenShift CLI
        if: steps.cache-oc.outputs.cache-hit != 'true'
        run: |
          wget https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/
      - name: Seed Personnel Data
        run: |
          cd "$GITHUB_WORKSPACE"
          oc login --token="${{ env.AUTH_TOKEN }}" --server="$CLUSTER"
          export OS_NAMESPACE_SUFFIX=${{ env.OS_NAMESPACE_SUFFIX }}
          make seed-oc-personnel
      - name: Seed BCWS Data
        run: |
            cd "$GITHUB_WORKSPACE"
            oc login --token="${{ env.AUTH_TOKEN }}" --server="$CLUSTER"
            export OS_NAMESPACE_SUFFIX=${{ env.OS_NAMESPACE_SUFFIX }}
            make seed-oc-bcws
      - name: Seed EMCR Data
        run: |
              cd "$GITHUB_WORKSPACE"
              oc login --token="${{ env.AUTH_TOKEN }}" --server="$CLUSTER"
              export OS_NAMESPACE_SUFFIX=${{ env.OS_NAMESPACE_SUFFIX }}
              make seed-oc-emcr