name: ZAP baseline scan
on:
  workflow_dispatch:
  push:
    

jobs: 
  zap_scan:    
    name: ZAP baseline scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ZAP baseline scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: https://tcloud-client-cd4869-dev.apps.gold.devops.gov.bc.ca/
          cmd_options: '-I'
      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: OWASP ZAP CORE Backend Report
          path: report_html.html